# -*-yaml-*-
application: pymty-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /favicon.ico
    upload: static/favicon.ico
    static_files: static/favicon.ico

  - url: /robots.txt
    upload: static/robots.txt
    static_files: static/robots.txt

  - url: /humans.txt
    upload: static/humans.txt
    static_files: static/humans.txt

  - url: /static
    static_dir: static

  - url: /.*
    script: pymty.app



libraries:
 - name: markupsafe
   version: latest
